# Burnout.guide
# =============

url: http://burnout.guide
repository: 'barvian/burnout.guide'
keywords:
  - burnout
  - health
  - life
  - work

secrets:
  typekit: 'gda7geu'
  reCaptcha:
    siteKey: '6Lf5TUwUAAAAANKAsm4baH_MwQ2NZcnx2dNX_Gfb'
    secret: 'zUGLT/hclZZKwfrRGE+e1FtAjjJyffE5qrFtAnePuhfRE2XggY+4PnOW0b1RxkLkZ4MZB7suH98OIA8W1HQQwhfqp9Af5asUhZLcRqo/JPp+vFMWBWK2Ss+MdA8iKO/D8q/TaGUJZgfcV6OVfxL57U5negIf9ZKD67DsjrqkyA8='

staticman:
  branch: 'development' # this must match staticman.yml
  
permalink: pretty

# Collections
# -----------

collections:
  articles:
    output: true
    permalink: /:path/

# Defaults
# --------

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
      author: "Maxwell Barvian"

# Build settings
# --------------

exclude:
  - CNAME
  - README.md

permalink: pretty

sass:
  style: compressed